ignore:
  - "**/GUI.scala"
  - "**/GuiService.scala"
  - "**/TUI.scala"
  - "**/TuiService.scala"
  - "**/CoreModule.scala"
  - "**/Observer.scala"

coverage:
  status:
    patch:
      default:
        target: 70%