name: Scala CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: compile
        run: sbt compile

  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        run:
          sudo -i
          apt install curl -y
      - name: Run tests
        run:
          sbt clean test jacoco
      - name: Upload report to Codecov
        run: |
          curl -s https://codecov.io/bash > .codecov
          chmod +x .codecov
          bash .codecov
